shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - '@firebase/util'
  - '@playwright/browser-chromium'
  - '@vscode/windows-process-tree'
  - esbuild
  - node-pty
  - protobufjs
